export const country = [
  {
    name: "Afghanistan",
    dial_code: "+93",
    code: "AF",
    year: "1970",
  },
  {
    name: "Aland Islands",
    dial_code: "+358",
    code: "AX",
    year: "1971",
  },
  {
    name: "Albania",
    dial_code: "+355",
    code: "AL",
    year: "1972",
  },
  {
    name: "Algeria",
    dial_code: "+213",
    code: "DZ",
    year: "1973",
  },
  {
    name: "AmericanSamoa",
    dial_code: "+1",
    code: "AS",
    year: "1974",
  },
  {
    name: "Andorra",
    dial_code: "+376",
    code: "AD",
    year: "1975",
  },
  {
    name: "Angola",
    dial_code: "+244",
    code: "AO",
    year: "1976",
  },
  {
    name: "Anguilla",
    dial_code: "+1",
    code: "AI",
    year: "1977",
  },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1",
    code: "AG",
    year: "1978",
  },
  {
    name: "Argentina",
    dial_code: "+54",
    code: "AR",
    year: "1979",
  },
  {
    name: "Armenia",
    dial_code: "+374",
    code: "AM",
    year: "1980",
  },
  {
    name: "Aruba",
    dial_code: "+297",
    code: "AW",
    year: "1981",
  },
  {
    name: "Australia",
    dial_code: "+61",
    code: "AU",
    year: "1982",
  },
  {
    name: "Austria",
    dial_code: "+43",
    code: "AT",
    year: "1983",
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    code: "AZ",
    year: "1984",
  },
  {
    name: "Bahamas",
    dial_code: "+1",
    code: "BS",
    year: "1985",
  },
  {
    name: "Bahrain",
    dial_code: "+973",
    code: "BH",
    year: "1986",
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    code: "BD",
    year: "1987",
  },
  {
    name: "Barbados",
    dial_code: "+1",
    code: "BB",
    year: "1988",
  },
  {
    name: "Belarus",
    dial_code: "+375",
    code: "BY",
    year: "1989",
  },
  {
    name: "Belgium",
    dial_code: "+32",
    code: "BE",
    year: "1990",
  },
  {
    name: "Belize",
    dial_code: "+501",
    code: "BZ",
    year: "1991",
  },
  {
    name: "Benin",
    dial_code: "+229",
    code: "BJ",
    year: "1992",
  },
  {
    name: "Bermuda",
    dial_code: "+1",
    code: "BM",
    year: "1993",
  },
  {
    name: "Bhutan",
    dial_code: "+975",
    code: "BT",
    year: "1994",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    code: "BO",
    year: "1995",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    code: "BA",
    year: "1996",
  },
  {
    name: "Botswana",
    dial_code: "+267",
    code: "BW",
    year: "1997",
  },
  {
    name: "Brazil",
    dial_code: "+55",
    code: "BR",
    year: "1998",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    code: "IO",
    year: "1999",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "+673",
    code: "BN",
    year: "2000",
  },
  {
    name: "Bulgaria",
    dial_code: "+359",
    code: "BG",
    year: "2001",
  },
  {
    name: "Burkina Faso",
    dial_code: "+226",
    code: "BF",
    year: "2002",
  },
  {
    name: "Burundi",
    dial_code: "+257",
    code: "BI",
    year: "2003",
  },
  {
    name: "Cambodia",
    dial_code: "+855",
    code: "KH",
    year: "2004",
  },
  {
    name: "Cameroon",
    dial_code: "+237",
    code: "CM",
    year: "2005",
  },
  {
    name: "Canada",
    dial_code: "+1",
    code: "CA",
    year: "2006",
  },
  {
    name: "Cape Verde",
    dial_code: "+238",
    code: "CV",
    year: "2007",
  },
  {
    name: "Cayman Islands",
    dial_code: "+1",
    code: "KY",
    year: "2008",
  },
  {
    name: "Central African Republic",
    dial_code: "+236",
    code: "CF",
    year: "2009",
  },
  {
    name: "Chad",
    dial_code: "+235",
    code: "TD",
    year: "2010",
  },
  {
    name: "Chile",
    dial_code: "+56",
    code: "CL",
    year: "2011",
  },
  {
    name: "China",
    dial_code: "+86",
    code: "CN",
    year: "2012",
  },
  {
    name: "Christmas Island",
    dial_code: "+61",
    code: "CX",
    year: "2013",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    code: "CC",
    year: "2014",
  },
  {
    name: "Colombia",
    dial_code: "+57",
    code: "CO",
    year: "2015",
  },
  {
    name: "Comoros",
    dial_code: "+269",
    code: "KM",
    year: "2016",
  },
  {
    name: "Congo",
    dial_code: "+242",
    code: "CG",
    year: "2017",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    code: "CD",
    year: "2018",
  },
  {
    name: "Cook Islands",
    dial_code: "+682",
    code: "CK",
    year: "2019",
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    code: "CR",
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "+225",
    code: "CI",
  },
  {
    name: "Croatia",
    dial_code: "+385",
    code: "HR",
  },
  {
    name: "Cuba",
    dial_code: "+53",
    code: "CU",
  },
  {
    name: "Cyprus",
    dial_code: "+357",
    code: "CY",
  },
  {
    name: "Czech Republic",
    dial_code: "+420",
    code: "CZ",
  },
  {
    name: "Denmark",
    dial_code: "+45",
    code: "DK",
  },
  {
    name: "Djibouti",
    dial_code: "+253",
    code: "DJ",
  },
  {
    name: "Dominica",
    dial_code: "+1",
    code: "DM",
  },
  {
    name: "Dominican Republic",
    dial_code: "+1",
    code: "DO",
  },
  {
    name: "Ecuador",
    dial_code: "+593",
    code: "EC",
  },
  {
    name: "Egypt",
    dial_code: "+20",
    code: "EG",
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    code: "SV",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "+240",
    code: "GQ",
  },
  {
    name: "Eritrea",
    dial_code: "+291",
    code: "ER",
  },
  {
    name: "Estonia",
    dial_code: "+372",
    code: "EE",
  },
  {
    name: "Ethiopia",
    dial_code: "+251",
    code: "ET",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    code: "FK",
  },
  {
    name: "Faroe Islands",
    dial_code: "+298",
    code: "FO",
  },
  {
    name: "Fiji",
    dial_code: "+679",
    code: "FJ",
  },
  {
    name: "Finland",
    dial_code: "+358",
    code: "FI",
  },
  {
    name: "France",
    dial_code: "+33",
    code: "FR",
  },
  {
    name: "French Guiana",
    dial_code: "+594",
    code: "GF",
  },
  {
    name: "French Polynesia",
    dial_code: "+689",
    code: "PF",
  },
  {
    name: "Gabon",
    dial_code: "+241",
    code: "GA",
  },
  {
    name: "Gambia",
    dial_code: "+220",
    code: "GM",
  },
  {
    name: "Georgia",
    dial_code: "+995",
    code: "GE",
  },
  {
    name: "Germany",
    dial_code: "+49",
    code: "DE",
  },
  {
    name: "Ghana",
    dial_code: "+233",
    code: "GH",
  },
  {
    name: "Gibraltar",
    dial_code: "+350",
    code: "GI",
  },
  {
    name: "Greece",
    dial_code: "+30",
    code: "GR",
  },
  {
    name: "Greenland",
    dial_code: "+299",
    code: "GL",
  },
  {
    name: "Grenada",
    dial_code: "+1",
    code: "GD",
  },
  {
    name: "Guadeloupe",
    dial_code: "+590",
    code: "GP",
  },
  {
    name: "Guam",
    dial_code: "+1",
    code: "GU",
  },
  {
    name: "Guatemala",
    dial_code: "+502",
    code: "GT",
  },
  {
    name: "Guernsey",
    dial_code: "+44",
    code: "GG",
  },
  {
    name: "Guinea",
    dial_code: "+224",
    code: "GN",
  },
  {
    name: "Guinea-Bissau",
    dial_code: "+245",
    code: "GW",
  },
  {
    name: "Guyana",
    dial_code: "+592",
    code: "GY",
  },
  {
    name: "Haiti",
    dial_code: "+509",
    code: "HT",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+39",
    code: "VA",
  },
  {
    name: "Honduras",
    dial_code: "+504",
    code: "HN",
  },
  {
    name: "Hong Kong",
    dial_code: "+852",
    code: "HK",
  },
  {
    name: "Hungary",
    dial_code: "+36",
    code: "HU",
  },
  {
    name: "Iceland",
    dial_code: "+354",
    code: "IS",
  },
  {
    name: "India",
    dial_code: "+91",
    code: "IN",
  },
  {
    name: "Indonesia",
    dial_code: "+62",
    code: "ID",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "+98",
    code: "IR",
  },
  {
    name: "Iraq",
    dial_code: "+964",
    code: "IQ",
  },
  {
    name: "Ireland",
    dial_code: "+353",
    code: "IE",
  },
  {
    name: "Isle of Man",
    dial_code: "+44",
    code: "IM",
  },
  {
    name: "Israel",
    dial_code: "+972",
    code: "IL",
  },
  {
    name: "Italy",
    dial_code: "+39",
    code: "IT",
  },
  {
    name: "Jamaica",
    dial_code: "+1",
    code: "JM",
  },
  {
    name: "Japan",
    dial_code: "+81",
    code: "JP",
  },
  {
    name: "Jersey",
    dial_code: "+44",
    code: "JE",
  },
  {
    name: "Jordan",
    dial_code: "+962",
    code: "JO",
  },
  {
    name: "Kazakhstan",
    dial_code: "+7",
    code: "KZ",
  },
  {
    name: "Kenya",
    dial_code: "+254",
    code: "KE",
  },
  {
    name: "Kiribati",
    dial_code: "+686",
    code: "KI",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "+850",
    code: "KP",
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "+82",
    code: "KR",
  },
  {
    name: "Kuwait",
    dial_code: "+965",
    code: "KW",
  },
  {
    name: "Kyrgyzstan",
    dial_code: "+996",
    code: "KG",
  },
  {
    name: "Laos",
    dial_code: "+856",
    code: "LA",
  },
  {
    name: "Latvia",
    dial_code: "+371",
    code: "LV",
  },
  {
    name: "Lebanon",
    dial_code: "+961",
    code: "LB",
  },
  {
    name: "Lesotho",
    dial_code: "+266",
    code: "LS",
  },
  {
    name: "Liberia",
    dial_code: "+231",
    code: "LR",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    code: "LY",
  },
  {
    name: "Liechtenstein",
    dial_code: "+423",
    code: "LI",
  },
  {
    name: "Lithuania",
    dial_code: "+370",
    code: "LT",
  },
  {
    name: "Luxembourg",
    dial_code: "+352",
    code: "LU",
  },
  {
    name: "Macao",
    dial_code: "+853",
    code: "MO",
  },
  {
    name: "Macedonia",
    dial_code: "+389",
    code: "MK",
  },
  {
    name: "Madagascar",
    dial_code: "+261",
    code: "MG",
  },
  {
    name: "Malawi",
    dial_code: "+265",
    code: "MW",
  },
  {
    name: "Malaysia",
    dial_code: "+60",
    code: "MY",
  },
  {
    name: "Maldives",
    dial_code: "+960",
    code: "MV",
  },
  {
    name: "Mali",
    dial_code: "+223",
    code: "ML",
  },
  {
    name: "Malta",
    dial_code: "+356",
    code: "MT",
  },
  {
    name: "Marshall Islands",
    dial_code: "+692",
    code: "MH",
  },
  {
    name: "Martinique",
    dial_code: "+596",
    code: "MQ",
  },
  {
    name: "Mauritania",
    dial_code: "+222",
    code: "MR",
  },
  {
    name: "Mauritius",
    dial_code: "+230",
    code: "MU",
  },
  {
    name: "Mayotte",
    dial_code: "+262",
    code: "YT",
  },
  {
    name: "Mexico",
    dial_code: "+52",
    code: "MX",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "+691",
    code: "FM",
  },
  {
    name: "Moldova",
    dial_code: "+373",
    code: "MD",
  },
  {
    name: "Monaco",
    dial_code: "+377",
    code: "MC",
  },
  {
    name: "Mongolia",
    dial_code: "+976",
    code: "MN",
  },
  {
    name: "Montenegro",
    dial_code: "+382",
    code: "ME",
  },
  {
    name: "Montserrat",
    dial_code: "+1",
    code: "MS",
  },
  {
    name: "Morocco",
    dial_code: "+212",
    code: "MA",
  },
  {
    name: "Mozambique",
    dial_code: "+258",
    code: "MZ",
  },
  {
    name: "Myanmar",
    dial_code: "+95",
    code: "MM",
  },
  {
    name: "Namibia",
    dial_code: "+264",
    code: "NA",
  },
  {
    name: "Nauru",
    dial_code: "+674",
    code: "NR",
  },
  {
    name: "Nepal",
    dial_code: "+977",
    code: "NP",
  },
  {
    name: "Netherlands",
    dial_code: "+31",
    code: "NL",
  },
  {
    name: "New Caledonia",
    dial_code: "+687",
    code: "NC",
  },
  {
    name: "New Zealand",
    dial_code: "+64",
    code: "NZ",
  },
  {
    name: "Nicaragua",
    dial_code: "+505",
    code: "NI",
  },
  {
    name: "Niger",
    dial_code: "+227",
    code: "NE",
  },
  {
    name: "Nigeria",
    dial_code: "+234",
    code: "NG",
  },
  {
    name: "Niue",
    dial_code: "+683",
    code: "NU",
  },
  {
    name: "Norfolk Island",
    dial_code: "+672",
    code: "NF",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "+1",
    code: "MP",
  },
  {
    name: "Norway",
    dial_code: "+47",
    code: "NO",
  },
  {
    name: "Oman",
    dial_code: "+968",
    code: "OM",
  },
  {
    name: "Pakistan",
    dial_code: "+92",
    code: "PK",
  },
  {
    name: "Palau",
    dial_code: "+680",
    code: "PW",
  },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "+970",
    code: "PS",
  },
  {
    name: "Panama",
    dial_code: "+507",
    code: "PA",
  },
  {
    name: "Papua New Guinea",
    dial_code: "+675",
    code: "PG",
  },
  {
    name: "Paraguay",
    dial_code: "+595",
    code: "PY",
  },
  {
    name: "Peru",
    dial_code: "+51",
    code: "PE",
  },
  {
    name: "Philippines",
    dial_code: "+63",
    code: "PH",
  },
  {
    name: "Poland",
    dial_code: "+48",
    code: "PL",
  },
  {
    name: "Portugal",
    dial_code: "+351",
    code: "PT",
  },
  {
    name: "Puerto Rico",
    dial_code: "+1",
    code: "PR",
  },
  {
    name: "Qatar",
    dial_code: "+974",
    code: "QA",
  },
  {
    name: "Romania",
    dial_code: "+40",
    code: "RO",
  },
  {
    name: "Russia",
    dial_code: "+7",
    code: "RU",
  },
  {
    name: "Rwanda",
    dial_code: "+250",
    code: "RW",
  },
  {
    name: "Reunion",
    dial_code: "+262",
    code: "RE",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "+590",
    code: "BL",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    code: "SH",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "+1",
    code: "KN",
  },
  {
    name: "Saint Lucia",
    dial_code: "+1",
    code: "LC",
  },
  {
    name: "Saint Martin",
    dial_code: "+590",
    code: "MF",
  },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    code: "PM",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1",
    code: "VC",
  },
  {
    name: "Samoa",
    dial_code: "+685",
    code: "WS",
  },
  {
    name: "San Marino",
    dial_code: "+378",
    code: "SM",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "+239",
    code: "ST",
  },
  {
    name: "Saudi Arabia",
    dial_code: "+966",
    code: "SA",
  },
  {
    name: "Senegal",
    dial_code: "+221",
    code: "SN",
  },
  {
    name: "Serbia",
    dial_code: "+381",
    code: "RS",
  },
  {
    name: "Seychelles",
    dial_code: "+248",
    code: "SC",
  },
  {
    name: "Sierra Leone",
    dial_code: "+232",
    code: "SL",
  },
  {
    name: "Singapore",
    dial_code: "+65",
    code: "SG",
  },
  {
    name: "Slovakia",
    dial_code: "+421",
    code: "SK",
  },
  {
    name: "Slovenia",
    dial_code: "+386",
    code: "SI",
  },
  {
    name: "Solomon Islands",
    dial_code: "+677",
    code: "SB",
  },
  {
    name: "Somalia",
    dial_code: "+252",
    code: "SO",
  },
  {
    name: "South Africa",
    dial_code: "+27",
    code: "ZA",
  },
  {
    name: "South Sudan",
    dial_code: "+211",
    code: "SS",
  },
  {
    name: "Spain",
    dial_code: "+34",
    code: "ES",
  },
  {
    name: "Sri Lanka",
    dial_code: "+94",
    code: "LK",
  },
  {
    name: "Sudan",
    dial_code: "+249",
    code: "SD",
  },
  {
    name: "Suriname",
    dial_code: "+597",
    code: "SR",
  },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    code: "SJ",
  },
  {
    name: "Swaziland",
    dial_code: "+268",
    code: "SZ",
  },
  {
    name: "Sweden",
    dial_code: "+46",
    code: "SE",
  },
  {
    name: "Switzerland",
    dial_code: "+41",
    code: "CH",
  },
  {
    name: "Syrian Arab Republic",
    dial_code: "+963",
    code: "SY",
  },
  {
    name: "Taiwan",
    dial_code: "+886",
    code: "TW",
  },
  {
    name: "Tajikistan",
    dial_code: "+992",
    code: "TJ",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "+255",
    code: "TZ",
  },
  {
    name: "Thailand",
    dial_code: "+66",
    code: "TH",
  },
  {
    name: "Timor-Leste",
    dial_code: "+670",
    code: "TL",
  },
  {
    name: "Togo",
    dial_code: "+228",
    code: "TG",
  },
  {
    name: "Tokelau",
    dial_code: "+690",
    code: "TK",
  },
  {
    name: "Tonga",
    dial_code: "+676",
    code: "TO",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "+1",
    code: "TT",
  },
  {
    name: "Tunisia",
    dial_code: "+216",
    code: "TN",
  },
  {
    name: "Turkey",
    dial_code: "+90",
    code: "TR",
  },
  {
    name: "Turkmenistan",
    dial_code: "+993",
    code: "TM",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "+1",
    code: "TC",
  },
  {
    name: "Tuvalu",
    dial_code: "+688",
    code: "TV",
  },
  {
    name: "Uganda",
    dial_code: "+256",
    code: "UG",
  },
  {
    name: "Ukraine",
    dial_code: "+380",
    code: "UA",
  },
  {
    name: "United Arab Emirates",
    dial_code: "+971",
    code: "AE",
  },
  {
    name: "United Kingdom",
    dial_code: "+44",
    code: "GB",
  },
  {
    name: "United States",
    dial_code: "+1",
    code: "US",
  },
  {
    name: "Uruguay",
    dial_code: "+598",
    code: "UY",
  },
  {
    name: "Uzbekistan",
    dial_code: "+998",
    code: "UZ",
  },
  {
    name: "Vanuatu",
    dial_code: "+678",
    code: "VU",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "+58",
    code: "VE",
  },
  {
    name: "Vietnam",
    dial_code: "+84",
    code: "VN",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "+1",
    code: "VG",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "+1",
    code: "VI",
  },
  {
    name: "Wallis and Futuna",
    dial_code: "+681",
    code: "WF",
  },
  {
    name: "Yemen",
    dial_code: "+967",
    code: "YE",
  },
  {
    name: "Zambia",
    dial_code: "+260",
    code: "ZM",
  },
  {
    name: "Zimbabwe",
    dial_code: "+263",
    code: "ZW",
  },
];

export const timeZons = [
  { name: "Africa/Abidjan" },
  { name: "Africa/Accra" },
  { name: "Africa/Addis_Ababa" },
  { name: "Africa/Algiers" },
  { name: "Africa/Asmara" },
  { name: "Africa/Asmera" },
  { name: "Africa/Bamako" },
  { name: "Africa/Bangui" },
  { name: "Africa/Banjul" },
  { name: "Africa/Bissau" },
  { name: "Africa/Blantyre" },
  { name: "Africa/Brazzaville" },
  { name: "Africa/Bujumbura" },
  { name: "Africa/Cairo" },
  { name: "Africa/Casablanca" },
  { name: "Africa/Ceuta" },
  { name: "Africa/Conakry" },
  { name: "Africa/Dakar" },
  { name: "Africa/Dar_es_Salaam" },
  { name: "Africa/Djibouti" },
  { name: "Africa/Douala" },
  { name: "Africa/El_Aaiun" },
  { name: "Africa/Freetown" },
  { name: "Africa/Gaborone" },
  { name: "Africa/Harare" },
  { name: "Africa/Johannesburg" },
  { name: "Africa/Juba" },
  { name: "Africa/Kampala" },
  { name: "Africa/Khartoum" },
  { name: "Africa/Kigali" },
  { name: "Africa/Kinshasa" },
  { name: "Africa/Lagos" },
  { name: "Africa/Libreville" },
  { name: "Africa/Lome" },
  { name: "Africa/Luanda" },
  { name: "Africa/Lubumbashi" },
  { name: "Africa/Lusaka" },
  { name: "Africa/Malabo" },
  { name: "Africa/Maputo" },
  { name: "Africa/Maseru" },
  { name: "Africa/Mbabane" },
  { name: "Africa/Mogadishu" },
  { name: "Africa/Monrovia" },
  { name: "Africa/Nairobi" },
  { name: "Africa/Ndjamena" },
  { name: "Africa/Niamey" },
  { name: "Africa/Nouakchott" },
  { name: "Africa/Ouagadougou" },
  { name: "Africa/Porto-Novo" },
  { name: "Africa/Sao_Tome" },
  { name: "Africa/Timbuktu" },
  { name: "Africa/Tripoli" },
  { name: "Africa/Tunis" },
  { name: "Africa/Windhoek" },
  { name: "America/Adak" },
  { name: "America/Anchorage" },
  { name: "America/Anguilla" },
  { name: "America/Antigua" },
  { name: "America/Araguaina" },
  { name: "America/Argentina/Buenos_Aires" },
  { name: "America/Argentina/Catamarca" },
  { name: "America/Argentina/ComodRivadavia" },
  { name: "America/Argentina/Cordoba" },
  { name: "America/Argentina/Jujuy" },
  { name: "America/Argentina/La_Rioja" },
  { name: "America/Argentina/Mendoza" },
  { name: "America/Argentina/Rio_Gallegos" },
  { name: "America/Argentina/Salta" },
  { name: "America/Argentina/San_Juan" },
  { name: "America/Argentina/San_Luis" },
  { name: "America/Argentina/Tucuman" },
  { name: "America/Argentina/Ushuaia" },
  { name: "America/Aruba" },
  { name: "America/Asuncion" },
  { name: "America/Atikokan" },
  { name: "America/Atka" },
  { name: "America/Bahia" },
  { name: "America/Bahia_Banderas" },
  { name: "America/Barbados" },
  { name: "America/Belem" },
  { name: "America/Belize" },
  { name: "America/Blanc-Sablon" },
  { name: "America/Boa_Vista" },
  { name: "America/Bogota" },
  { name: "America/Boise" },
  { name: "America/Buenos_Aires" },
  { name: "America/Cambridge_Bay" },
  { name: "America/Campo_Grande" },
  { name: "America/Cancun" },
  { name: "America/Caracas" },
  { name: "America/Catamarca" },
  { name: "America/Cayenne" },
  { name: "America/Cayman" },
  { name: "America/Chicago" },
  { name: "America/Chihuahua" },
  { name: "America/Coral_Harbour" },
  { name: "America/Cordoba" },
  { name: "America/Costa_Rica" },
  { name: "America/Creston" },
  { name: "America/Cuiaba" },
  { name: "America/Curacao" },
  { name: "America/Danmarkshavn" },
  { name: "America/Dawson" },
  { name: "America/Dawson_Creek" },
  { name: "America/Denver" },
  { name: "America/Detroit" },
  { name: "America/Dominica" },
  { name: "America/Edmonton" },
  { name: "America/Eirunepe" },
  { name: "America/El_Salvador" },
  { name: "America/Ensenada" },
  { name: "America/Fort_Nelson" },
  { name: "America/Fort_Wayne" },
  { name: "America/Fortaleza" },
  { name: "America/Glace_Bay" },
  { name: "America/Godthab" },
  { name: "America/Goose_Bay" },
  { name: "America/Grand_Turk" },
  { name: "America/Grenada" },
  { name: "America/Guadeloupe" },
  { name: "America/Guatemala" },
  { name: "America/Guayaquil" },
  { name: "America/Guyana" },
  { name: "America/Halifax" },
  { name: "America/Havana" },
  { name: "America/Hermosillo" },
  { name: "America/Indiana/Indianapolis" },
  { name: "America/Indiana/Knox" },
  { name: "America/Indiana/Marengo" },
  { name: "America/Indiana/Petersburg" },
  { name: "America/Indiana/Tell_City" },
  { name: "America/Indiana/Vevay" },
  { name: "America/Indiana/Vincennes" },
  { name: "America/Indiana/Winamac" },
  { name: "America/Indianapolis" },
  { name: "America/Inuvik" },
  { name: "America/Iqaluit" },
  { name: "America/Jamaica" },
  { name: "America/Jujuy" },
  { name: "America/Juneau" },
  { name: "America/Kentucky/Louisville" },
  { name: "America/Kentucky/Monticello" },
  { name: "America/Knox_IN" },
  { name: "America/Kralendijk" },
  { name: "America/La_Paz" },
  { name: "America/Lima" },
  { name: "America/Los_Angeles" },
  { name: "America/Louisville" },
  { name: "America/Lower_Princes" },
  { name: "America/Maceio" },
  { name: "America/Managua" },
  { name: "America/Manaus" },
  { name: "America/Marigot" },
  { name: "America/Martinique" },
  { name: "America/Matamoros" },
  { name: "America/Mazatlan" },
  { name: "America/Mendoza" },
  { name: "America/Menominee" },
  { name: "America/Merida" },
  { name: "America/Metlakatla" },
  { name: "America/Mexico_City" },
  { name: "America/Miquelon" },
  { name: "America/Moncton" },
  { name: "America/Monterrey" },
  { name: "America/Montevideo" },
  { name: "America/Montreal" },
  { name: "America/Montserrat" },
  { name: "America/Nassau" },
  { name: "America/New_York" },
  { name: "America/Nipigon" },
  { name: "America/Nome" },
  { name: "America/Noronha" },
  { name: "America/North_Dakota/Beulah" },
  { name: "America/North_Dakota/Center" },
  { name: "America/North_Dakota/New_Salem" },
  { name: "America/Nuuk" },
  { name: "America/Ojinaga" },
  { name: "America/Panama" },
  { name: "America/Pangnirtung" },
  { name: "America/Paramaribo" },
  { name: "America/Phoenix" },
  { name: "America/Port-au-Prince" },
  { name: "America/Port_of_Spain" },
  { name: "America/Porto_Acre" },
  { name: "America/Porto_Velho" },
  { name: "America/Puerto_Rico" },
  { name: "America/Punta_Arenas" },
  { name: "America/Rainy_River" },
  { name: "America/Rankin_Inlet" },
  { name: "America/Recife" },
  { name: "America/Regina" },
  { name: "America/Resolute" },
  { name: "America/Rio_Branco" },
  { name: "America/Rosario" },
  { name: "America/Santa_Isabel" },
  { name: "America/Santarem" },
  { name: "America/Santiago" },
  { name: "America/Santo_Domingo" },
  { name: "America/Sao_Paulo" },
  { name: "America/Scoresbysund" },
  { name: "America/Shiprock" },
  { name: "America/Sitka" },
  { name: "America/St_Barthelemy" },
  { name: "America/St_Johns" },
  { name: "America/St_Kitts" },
  { name: "America/St_Lucia" },
  { name: "America/St_Thomas" },
  { name: "America/St_Vincent" },
  { name: "America/Swift_Current" },
  { name: "America/Tegucigalpa" },
  { name: "America/Thule" },
  { name: "America/Thunder_Bay" },
  { name: "America/Tijuana" },
  { name: "America/Toronto" },
  { name: "America/Tortola" },
  { name: "America/Vancouver" },
  { name: "America/Virgin" },
  { name: "America/Whitehorse" },
  { name: "America/Winnipeg" },
  { name: "America/Yakutat" },
  { name: "America/Yellowknife" },
  { name: "Antarctica/Casey" },
  { name: "Antarctica/Davis" },
  { name: "Antarctica/DumontDUrville" },
  { name: "Antarctica/Macquarie" },
  { name: "Antarctica/Mawson" },
  { name: "Antarctica/McMurdo" },
  { name: "Antarctica/Palmer" },
  { name: "Antarctica/Rothera" },
  { name: "Antarctica/South_Pole" },
  { name: "Antarctica/Syowa" },
  { name: "Antarctica/Troll" },
  { name: "Antarctica/Vostok" },
  { name: "Arctic/Longyearbyen" },
  { name: "Asia/Aden" },
  { name: "Asia/Almaty" },
  { name: "Asia/Amman" },
  { name: "Asia/Anadyr" },
  { name: "Asia/Aqtau" },
  { name: "Asia/Aqtobe" },
  { name: "Asia/Ashgabat" },
  { name: "Asia/Ashkhabad" },
  { name: "Asia/Atyrau" },
  { name: "Asia/Baghdad" },
  { name: "Asia/Bahrain" },
  { name: "Asia/Baku" },
  { name: "Asia/Bangkok" },
  { name: "Asia/Barnaul" },
  { name: "Asia/Beirut" },
  { name: "Asia/Bishkek" },
  { name: "Asia/Brunei" },
  { name: "Asia/Calcutta" },
  { name: "Asia/Chita" },
  { name: "Asia/Choibalsan" },
  { name: "Asia/Chongqing" },
  { name: "Asia/Chungking" },
  { name: "Asia/Colombo" },
  { name: "Asia/Dacca" },
  { name: "Asia/Damascus" },
  { name: "Asia/Dhaka" },
  { name: "Asia/Dili" },
  { name: "Asia/Dubai" },
  { name: "Asia/Dushanbe" },
  { name: "Asia/Famagusta" },
  { name: "Asia/Gaza" },
  { name: "Asia/Harbin" },
  { name: "Asia/Hebron" },
  { name: "Asia/Ho_Chi_Minh" },
  { name: "Asia/Hong_Kong" },
  { name: "Asia/Hovd" },
  { name: "Asia/Irkutsk" },
  { name: "Asia/Istanbul" },
  { name: "Asia/Jakarta" },
  { name: "Asia/Jayapura" },
  { name: "Asia/Jerusalem" },
  { name: "Asia/Kabul" },
  { name: "Asia/Kamchatka" },
  { name: "Asia/Karachi" },
  { name: "Asia/Kashgar" },
  { name: "Asia/Kathmandu" },
  { name: "Asia/Katmandu" },
  { name: "Asia/Khandyga" },
  { name: "Asia/Kolkata" },
  { name: "Asia/Krasnoyarsk" },
  { name: "Asia/Kuala_Lumpur" },
  { name: "Asia/Kuching" },
  { name: "Asia/Kuwait" },
  { name: "Asia/Macao" },
  { name: "Asia/Macau" },
  { name: "Asia/Magadan" },
  { name: "Asia/Makassar" },
  { name: "Asia/Manila" },
  { name: "Asia/Muscat" },
  { name: "Asia/Nicosia" },
  { name: "Asia/Novokuznetsk" },
  { name: "Asia/Novosibirsk" },
  { name: "Asia/Omsk" },
  { name: "Asia/Oral" },
  { name: "Asia/Phnom_Penh" },
  { name: "Asia/Pontianak" },
  { name: "Asia/Pyongyang" },
  { name: "Asia/Qatar" },
  { name: "Asia/Qostanay" },
  { name: "Asia/Qyzylorda" },
  { name: "Asia/Rangoon" },
  { name: "Asia/Riyadh" },
  { name: "Asia/Saigon" },
  { name: "Asia/Sakhalin" },
  { name: "Asia/Samarkand" },
  { name: "Asia/Seoul" },
  { name: "Asia/Shanghai" },
  { name: "Asia/Singapore" },
  { name: "Asia/Srednekolymsk" },
  { name: "Asia/Taipei" },
  { name: "Asia/Tashkent" },
  { name: "Asia/Tbilisi" },
  { name: "Asia/Tehran" },
  { name: "Asia/Tel_Aviv" },
  { name: "Asia/Thimbu" },
  { name: "Asia/Thimphu" },
  { name: "Asia/Tokyo" },
  { name: "Asia/Tomsk" },
  { name: "Asia/Ujung_Pandang" },
  { name: "Asia/Ulaanbaatar" },
  { name: "Asia/Ulan_Bator" },
  { name: "Asia/Urumqi" },
  { name: "Asia/Ust-Nera" },
  { name: "Asia/Vientiane" },
  { name: "Asia/Vladivostok" },
  { name: "Asia/Yakutsk" },
  { name: "Asia/Yangon" },
  { name: "Asia/Yekaterinburg" },
  { name: "Asia/Yerevan" },
  { name: "Atlantic/Azores" },
  { name: "Atlantic/Bermuda" },
  { name: "Atlantic/Canary" },
  { name: "Atlantic/Cape_Verde" },
  { name: "Atlantic/Faeroe" },
  { name: "Atlantic/Faroe" },
  { name: "Atlantic/Jan_Mayen" },
  { name: "Atlantic/Madeira" },
  { name: "Atlantic/Reykjavik" },
  { name: "Atlantic/South_Georgia" },
  { name: "Atlantic/St_Helena" },
  { name: "Atlantic/Stanley" },
  { name: "Australia/ACT" },
  { name: "Australia/Adelaide" },
  { name: "Australia/Brisbane" },
  { name: "Australia/Broken_Hill" },
  { name: "Australia/Canberra" },
  { name: "Australia/Currie" },
  { name: "Australia/Darwin" },
  { name: "Australia/Eucla" },
  { name: "Australia/Hobart" },
  { name: "Australia/LHI" },
  { name: "Australia/Lindeman" },
  { name: "Australia/Lord_Howe" },
  { name: "Australia/Melbourne" },
  { name: "Australia/NSW" },
  { name: "Australia/North" },
  { name: "Australia/Perth" },
  { name: "Australia/Queensland" },
  { name: "Australia/South" },
  { name: "Australia/Sydney" },
  { name: "Australia/Tasmania" },
  { name: "Australia/Victoria" },
  { name: "Australia/West" },
  { name: "Australia/Yancowinna" },
  { name: "Brazil/Acre" },
  { name: "Brazil/DeNoronha" },
  { name: "Brazil/East" },
  { name: "Brazil/West" },
  { name: "CET" },
  { name: "CST6CDT" },
  { name: "Canada/Atlantic" },
  { name: "Canada/Central" },
  { name: "Canada/Eastern" },
  { name: "Canada/Mountain" },
  { name: "Canada/Newfoundland" },
  { name: "Canada/Pacific" },
  { name: "Canada/Saskatchewan" },
  { name: "Canada/Yukon" },
  { name: "Chile/Continental" },
  { name: "Chile/EasterIsland" },
  { name: "Cuba" },
  { name: "EET" },
  { name: "EST" },
  { name: "EST5EDT" },
  { name: "Egypt" },
  { name: "Eire" },
  { name: "Etc/GMT" },
  { name: "Etc/GMT+0" },
  { name: "Etc/GMT+1" },
  { name: "Etc/GMT+10" },
  { name: "Etc/GMT+11" },
  { name: "Etc/GMT+12" },
  { name: "Etc/GMT+2" },
  { name: "Etc/GMT+3" },
  { name: "Etc/GMT+4" },
  { name: "Etc/GMT+5" },
  { name: "Etc/GMT+6" },
  { name: "Etc/GMT+7" },
  { name: "Etc/GMT+8" },
  { name: "Etc/GMT+9" },
  { name: "Etc/GMT-0" },
  { name: "Etc/GMT-1" },
  { name: "Etc/GMT-10" },
  { name: "Etc/GMT-11" },
  { name: "Etc/GMT-12" },
  { name: "Etc/GMT-13" },
  { name: "Etc/GMT-14" },
  { name: "Etc/GMT-2" },
  { name: "Etc/GMT-3" },
  { name: "Etc/GMT-4" },
  { name: "Etc/GMT-5" },
  { name: "Etc/GMT-6" },
  { name: "Etc/GMT-7" },
  { name: "Etc/GMT-8" },
  { name: "Etc/GMT-9" },
  { name: "Etc/GMT0" },
  { name: "Etc/Greenwich" },
  { name: "Etc/UCT" },
  { name: "Etc/UTC" },
  { name: "Etc/Universal" },
  { name: "Etc/Zulu" },
  { name: "Europe/Amsterdam" },
  { name: "Europe/Andorra" },
  { name: "Europe/Astrakhan" },
  { name: "Europe/Athens" },
  { name: "Europe/Belfast" },
  { name: "Europe/Belgrade" },
  { name: "Europe/Berlin" },
  { name: "Europe/Bratislava" },
  { name: "Europe/Brussels" },
  { name: "Europe/Bucharest" },
  { name: "Europe/Budapest" },
  { name: "Europe/Busingen" },
  { name: "Europe/Chisinau" },
  { name: "Europe/Copenhagen" },
  { name: "Europe/Dublin" },
  { name: "Europe/Gibraltar" },
  { name: "Europe/Guernsey" },
  { name: "Europe/Helsinki" },
  { name: "Europe/Isle_of_Man" },
  { name: "Europe/Istanbul" },
  { name: "Europe/Jersey" },
  { name: "Europe/Kaliningrad" },
  { name: "Europe/Kiev" },
  { name: "Europe/Kirov" },
  { name: "Europe/Lisbon" },
  { name: "Europe/Ljubljana" },
  { name: "Europe/London" },
  { name: "Europe/Luxembourg" },
  { name: "Europe/Madrid" },
  { name: "Europe/Malta" },
  { name: "Europe/Mariehamn" },
  { name: "Europe/Minsk" },
  { name: "Europe/Monaco" },
  { name: "Europe/Moscow" },
  { name: "Europe/Nicosia" },
  { name: "Europe/Oslo" },
  { name: "Europe/Paris" },
  { name: "Europe/Podgorica" },
  { name: "Europe/Prague" },
  { name: "Europe/Riga" },
  { name: "Europe/Rome" },
  { name: "Europe/Samara" },
  { name: "Europe/San_Marino" },
  { name: "Europe/Sarajevo" },
  { name: "Europe/Saratov" },
  { name: "Europe/Simferopol" },
  { name: "Europe/Skopje" },
  { name: "Europe/Sofia" },
  { name: "Europe/Stockholm" },
  { name: "Europe/Tallinn" },
  { name: "Europe/Tirane" },
  { name: "Europe/Tiraspol" },
  { name: "Europe/Ulyanovsk" },
  { name: "Europe/Uzhgorod" },
  { name: "Europe/Vaduz" },
  { name: "Europe/Vatican" },
  { name: "Europe/Vienna" },
  { name: "Europe/Vilnius" },
  { name: "Europe/Volgograd" },
  { name: "Europe/Warsaw" },
  { name: "Europe/Zagreb" },
  { name: "Europe/Zaporozhye" },
  { name: "Europe/Zurich" },
  { name: "GB" },
  { name: "GB-Eire" },
  { name: "GMT" },
  { name: "GMT+0" },
  { name: "GMT-0" },
  { name: "GMT0" },
  { name: "Greenwich" },
  { name: "HST" },
  { name: "Hongkong" },
  { name: "Iceland" },
  { name: "Indian/Antananarivo" },
  { name: "Indian/Chagos" },
  { name: "Indian/Christmas" },
  { name: "Indian/Cocos" },
  { name: "Indian/Comoro" },
  { name: "Indian/Kerguelen" },
  { name: "Indian/Mahe" },
  { name: "Indian/Maldives" },
  { name: "Indian/Mauritius" },
  { name: "Indian/Mayotte" },
  { name: "Indian/Reunion" },
  { name: "Iran" },
  { name: "Israel" },
  { name: "Jamaica" },
  { name: "Japan" },
  { name: "Kwajalein" },
  { name: "Libya" },
  { name: "MET" },
  { name: "MST" },
  { name: "MST7MDT" },
  { name: "Mexico/BajaNorte" },
  { name: "Mexico/BajaSur" },
  { name: "Mexico/General" },
  { name: "NZ" },
  { name: "NZ-CHAT" },
  { name: "Navajo" },
  { name: "PRC" },
  { name: "PST8PDT" },
  { name: "Pacific/Apia" },
  { name: "Pacific/Auckland" },
  { name: "Pacific/Bougainville" },
  { name: "Pacific/Chatham" },
  { name: "Pacific/Chuuk" },
  { name: "Pacific/Easter" },
  { name: "Pacific/Efate" },
  { name: "Pacific/Enderbury" },
  { name: "Pacific/Fakaofo" },
  { name: "Pacific/Fiji" },
  { name: "Pacific/Funafuti" },
  { name: "Pacific/Galapagos" },
  { name: "Pacific/Gambier" },
  { name: "Pacific/Guadalcanal" },
  { name: "Pacific/Guam" },
  { name: "Pacific/Honolulu" },
  { name: "Pacific/Johnston" },
  { name: "Pacific/Kiritimati" },
  { name: "Pacific/Kosrae" },
  { name: "Pacific/Kwajalein" },
  { name: "Pacific/Majuro" },
  { name: "Pacific/Marquesas" },
  { name: "Pacific/Midway" },
  { name: "Pacific/Nauru" },
  { name: "Pacific/Niue" },
  { name: "Pacific/Norfolk" },
  { name: "Pacific/Noumea" },
  { name: "Pacific/Pago_Pago" },
  { name: "Pacific/Palau" },
  { name: "Pacific/Pitcairn" },
  { name: "Pacific/Pohnpei" },
  { name: "Pacific/Ponape" },
  { name: "Pacific/Port_Moresby" },
  { name: "Pacific/Rarotonga" },
  { name: "Pacific/Saipan" },
  { name: "Pacific/Samoa" },
  { name: "Pacific/Tahiti" },
  { name: "Pacific/Tarawa" },
  { name: "Pacific/Tongatapu" },
  { name: "Pacific/Truk" },
  { name: "Pacific/Wake" },
  { name: "Pacific/Wallis" },
  { name: "Pacific/Yap" },
  { name: "Poland" },
  { name: "Portugal" },
  { name: "ROC" },
  { name: "ROK" },
  { name: "Singapore" },
  { name: "Turkey" },
  { name: "UCT" },
  { name: "US/Alaska" },
  { name: "US/Aleutian" },
  { name: "US/Arizona" },
  { name: "US/Central" },
  { name: "US/East-Indiana" },
  { name: "US/Eastern" },
  { name: "US/Hawaii" },
  { name: "US/Indiana-Starke" },
  { name: "US/Michigan" },
  { name: "US/Mountain" },
  { name: "US/Pacific" },
  { name: "US/Samoa" },
  { name: "UTC" },
  { name: "Universal" },
  { name: "W-SU" },
  { name: "WET" },
  { name: "Zulu" },
];
